# docker run -it --rm  --name n8n  -p 5678:5678  -v n8n_data:/home/node/.n8n  -e N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE:true  -e N8N_EDITOR_BASE_URL=https://realizing-colin-supernumerous.ngrok-free.dev  -e WEBHOOK_URL:https://realizing-colin-supernumerous.ngrok-free.dev  -e N8N_DEFAULT_BINARY_DATA_MODE:filesystem   docker.n8n.io/n8nio/n8n

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_EDITOR_BASE_URL=https://realizing-colin-supernumerous.ngrok-free.dev
      - WEBHOOK_URL=https://realizing-colin-supernumerous.ngrok-free.dev
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command:
      - "http"
      - "n8n:5678"
      - "--url=realizing-colin-supernumerous.ngrok-free.dev"
    environment:
      - NGROK_AUTHTOKEN=33Y1ZApXl7AOVDckQ3XRULoOSs2_7JV7DfYmU6tDE73HWE26Z
    depends_on:
      - n8n

volumes:
  n8n_data:
    external: true

